ScreenTaker/Models/Image.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ScreenTaker.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Image
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Image()
        {
            this.GroupShares = new HashSet<GroupShare>();
            this.UserShares = new HashSet<UserShare>();
            this.Tags = new HashSet<Tag>();
        }
    
        public int FolderId { get; set; }
        public bool IsPublic { get; set; }
        public string SharedCode { get; set; }
        public string Name { get; set; }
        public Nullable<System.DateTime> PublicationDate { get; set; }
        public int Id { get; set; }
        public Nullable<int> ServerFolderId { get; set; }
    
        public virtual Folder Folder { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GroupShare> GroupShares { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UserShare> UserShares { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tag> Tags { get; set; }
        public virtual ServerFolder ServerFolder { get; set; }
    }
}

ScreenTaker/Controllers/EditController.cs
using ScreenTaker.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Globalization;
using System.Threading;
using Microsoft.AspNet.Identity;
using Microsoft.AspNet.Identity.Owin;

namespace ScreenTaker.Controllers
{
    [Authorize]
    public class EditController : GeneralController
    {
        private ScreenTakerEntities _entities = new ScreenTakerEntities();
        public ActionResult Index(string lang = "en")
        {
            ViewBag.Localize = getLocale();
            return View("UserGroups",new { lang = getLocale() });
        }

        public ActionResult EditImage(string lang = "en")
        {
            ViewBag.Localize = getLocale();
            return View("EditImage", new { lang = getLocale() });
        }

        public ActionResult UserGroups(int selectedId=-1)
        {
            Thread.CurrentThread.CurrentUICulture = new CultureInfo(getLocale());
            ViewBag.Localize = getLocale();
            using (var transaction = _entities.Database.BeginTransaction())
            {                                   
                try
                {
                    ApplicationUser user = System.Web.HttpContext.Current.GetOwinContext().GetUserManager<ApplicationUserManager>().FindById(User.Identity.GetUserId<int>());
                    if (user != null)
                    {
                        var email = user.Email;                        
                        ViewBag.Groups = _entities.PersonGroups.Where(w=>w.Person.Email==email).Select(s => s).ToList();
                        ViewBag.GroupMemberCounts = _entities.PersonGroups.Where(w => w.Person.Email == email).Select(s => s.GroupMembers.Count).ToList();
                        if (selectedId == -1)
                            selectedId = _entities.PersonGroups.Where(w => w.Person.Email == email).Select(s => s.Id).FirstOrDefault();
                        ViewBag.selectedId = selectedId;
                    }

                    var emails = from p in _entities.People
                                 join m in _entities.GroupMembers
                                 on p.Id equals m.PersonId
                                 where m.GroupId == selectedId
                                 select new { ID = m.GroupId, Email = p.Email, p.AvatarFile };              
                    if (emails.Any())
                    {
                        ViewBag.Emails = emails.Select(s => s.Email).ToList();
                        var baseUrl = GetBaseUrl();                        
                        IList<string> avatars = new List<string>();
                        foreach (var e in emails)
                        {                          
                            if (e.AvatarFile == null || !System.IO.File.Exists(Server.MapPath("/avatars/") + e.AvatarFile + "_50.png"))
                                avatars.Add(getUserAvatar("user_50"));
                            else
                                avatars.Add(getUserAvatar(e.AvatarFile + "_50"));
                        }
                        ViewBag.Avatars = avatars;
                    }                                                  
                    transaction.Commit();
                }
                catch (Exception ex)
                {
                    transaction.Rollback();
	            ViewBag.MessageContent = ex.Message;
                    return View("Message", new { lang = getLocale() });
                }
            }
            return View("UserGroups", new { lang = getLocale() });
        }

        [AllowAnonymous]
        public void ChangeLocalization(string request, string lang = "en")
        {
            
            if (request.Equals("/") || request.Equals(""))
            {
                request = GetBaseUrl() +"Home/Welcome";
            }
            if (request.Contains("?"))
            {
                if (request.Contains("lang"))
                {
                    int index = request.IndexOf("lang=");
                    string sub = request.Substring(index, 7);
                    request = request.Replace(sub, "lang=" + lang);
                }
                else
                {
                    request += "&lang=" + lang;
                }
            }
            else
            {
                request += "?lang=" + lang;
            }
            Session["Locale"] = lang;
            ViewBag.Localize = getLocale();
            Response.Redirect(request);
        }

        public ActionResult CreateGroup(string name)
        {
            Thread.CurrentThread.CurrentUICulture = new CultureInfo(getLocale());
            ViewBag.Localize = getLocale();
            int idToRedirect = 0;
            using (var transaction = _entities.Database.BeginTransaction())
            {
                try
                {                   
                    if (name==null||name.Length==0)
                        throw new Exception(Resources.Resource.ERR_EMPTY_FIELD);
                    var group = new PersonGroup();
                    group.Name = name;                    

                    ApplicationUser user = System.Web.HttpContext.Current.GetOwinContext().GetUserManager<ApplicationUserManager>().FindById(User.Identity.GetUserId<int>());
                    if (user != null)
                    {
                        if (_entities.PersonGroups.Where(w => w.Name == name&&w.PersonId==user.Id).Any())
                            throw new Exception(Resources.Resource.ERR_GROUP_ALREDY);
                        var email = user.Email;
                        group.PersonId = _entities.People.Where(w=>w.Email==email).Select(s=>s.Id).FirstOrDefault();
                    }
                    else
                        group.PersonId = null;
                    _entities.PersonGroups.Add(group);
                    _entities.SaveChanges();
                    idToRedirect = group.Id;
                    transaction.Commit();
                }
                catch (Exception ex)
                {
                    transaction.Rollback();
                    TempData["MessageContent"] = ex.Message;
                }
            }
            return RedirectToAction("Partial_GroupsAndEmails", new {selectedId=idToRedirect, lang = getLocale()  });
        }


        public ActionResult RemoveGroup(int selectedId = 0)
        {
            Thread.CurrentThread.CurrentUICulture = new CultureInfo(getLocale());
            ViewBag.Localize = getLocale();
            int idToRedirect = 0;
            using (var transaction = _entities.Database.BeginTransaction())
            {
                try
                {
                    var groupId = selectedId;

                    if (_entities.GroupMembers.Where(w => w.GroupId == groupId).Any())
            {
                var groupMembers = _entities.GroupMembers.Where(w => w.GroupId == groupId).ToList();
                for (var i = 0; i < groupMembers.Count; i++)
                    if (groupMembers[i] != null)
                        _entities.GroupMembers.Remove(groupMembers[i]);
            }
            if (_entities.GroupShares.Where(w => w.GroupId == groupId).Any())
            {
                var groupShares= _entities.GroupShares.Where(w => w.GroupId == groupId).ToList();
                for (var i = 0; i < groupShares.Count; i++)
                    if (groupShares[i] != null)
                        _entities.GroupShares.Remove(groupShares[i]);
            }
                var group = _entities.PersonGroups.Where(w => w.Id == groupId).FirstOrDefault();
            if (group != null)
                _entities.PersonGroups.Remove(group);
            ApplicationUser user = System.Web.HttpContext.Current.GetOwinContext().GetUserManager<ApplicationUserManager>().FindById(User.Identity.GetUserId<int>());
                    if (user != null)
                    {
                        var email = user.Email;
                idToRedirect = _entities.PersonGroups.Where(w => w.Person.Email == email).Select(s => s.Id).FirstOrDefault();
            }
                    _entities.SaveChanges();
                    transaction.Commit();
                }
                catch (Exception ex)
                {
                    transaction.Rollback();
                    TempData["MessageContent"] = ex.Message;
                }
            }
            return RedirectToAction("Partial_GroupsAndEmails", new { selectedId = idToRedirect, lang = getLocale()  });
        }

        public ActionResult AddUser(int selectedId,string email)
        {
            Thread.CurrentThread.CurrentUICulture = new CultureInfo(getLocale());
            ViewBag.Localize = getLocale();
            using (var transaction = _entities.Database.BeginTransaction())
            {
                try
                {
                    if (email == null || email.Length == 0)
                        throw new Exception(Resources.Resource.ERR_EMPTY_FIELD);
                    if (!_entities.People.Where(s => s.Email.Equals(email)).Any())
                        throw new Exception(Resources.Resource.ERR_EMAIL_NOT_EXIST);
                    if (_entities.People.Where(w => w.Email == email && w.GroupMembers.Where(w2 => w2.GroupId == selectedId).Any()).Any())
                        throw new Exception(Resources.Resource.ERR_USER_ALREDY);                    
                    ApplicationUser user = System.Web.HttpContext.Current.GetOwinContext().GetUserManager<ApplicationUserManager>().FindById(User.Identity.GetUserId<int>());
                    if (user != null)
                    {
                        
                        if (user != null && email==user.Email)
                                throw new Exception(Resources.Resource.ERR_ADD_YOURSELF);
                        var friend = _entities.People.Where(w => w.Email == email).FirstOrDefault();

ScreenTaker/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
    if (!Request.QueryString["lang"].IsEmpty())
    {
        Culture = UICulture = Request.QueryString["lang"];
    }
    else
    {
        Culture = UICulture = ViewBag.Localize ?? "en";
    }
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<p>Use this area to provide additional information.</p>

ScreenTaker/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Welcome to ScreenTaker";
    int counter = 0;
    ViewBag.LorenIpsum = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nulla quam velit, vulputate eu pharetra nec, mattis ac neque. Duis vulputate commodo lectus, ac blandit elit tincidunt id. Sed rhoncus, tortor sed eleifend tristique, tortor mauris molestie elit, et lacinia ipsum quam nec dui. Quisque nec mauris sit amet elit iaculis pretium sit amet quis magna. Aenean velit odio, elementum in tempus ut, vehicula eu diam. Pellentesque rhoncus aliquam mattis. Ut vulputate eros sed felis sodales nec vulputate justo hendrerit. Vivamus varius pretium ligula, a aliquam odio euismod sit amet. Quisque laoreet sem sit amet orci ullamcorper at ultricies metus viverra. Pellentesque arcu mauris, malesuada quis ornare accumsan, blandit sed diam.";
}


<div class="row">
    <div class="col-lg-12 col-md-9 col-sm-12">
        <div class="jumbotron" >
            <h1 class="text-color">ScreenTaker</h1>
            <p class="lead-site">@ViewBag.LorenIpsum</p>

            <div class="row">
                <div class="col-md-4">
                </div>
                <div class="col-md-4">
                    @using (Html.BeginForm("", "Home/Index", FormMethod.Post, new { enctype = "multipart/form-data" }))
                    { 
                        <input id="fileInput" style="visibility:collapse" type="file" name="file" onchange="document.getElementById('fileSubmit').click();" />
                        <input id="fileSubmit" style="visibility:collapse" type="submit" value="bla" />
                        <input type="button" class="btn btn-primary btn-lg center-block" style="width:200px; height:70px;" value="Upload image" onclick="document.getElementById('fileInput').click();" />
                    }
                </div>
                <div class="col-md-4">
                </div>
            </div>
        </div>
    </div>
</div>


<div class="row">
    <div class="col-lg-12 col-md-9 col-sm-12">
        <div class="container">
            <div class="row">
                <div class="col-md-2">
                </div>
                <div class="col-md-8">
                    <h2>About Screen Taker</h2>
                    <p>@ViewBag.LorenIpsum</p>
                </div>
                <div class="col-md-1">
                </div>
            </div>
            <div class="row">
                <div class="col-md-2">
                </div>
                <div class="col-md-8">
                    <h2>Capturing full screen</h2>
                    <p>@ViewBag.LorenIpsum</p>
                    <img src="~/img/printscreen.png" class="welcome-image" />
                </div>
                <div class="col-md-2">
                </div>
            </div>
            <div class="row">
                <div class="col-md-2">
                </div>
                <div class="col-md-8">
                    <h2>Features</h2>
                    <p>@ViewBag.LorenIpsum</p>
                </div>
                <div class="col-md-2">
                </div>
            </div>
        </div>
    </div>
</div>
        

ScreenTaker/Views/Home/Message.cshtml
@{
    ViewBag.Title = "Opps...";
    Layout = "~/Views/Shared/_Layout.cshtml";
    if (!Request.QueryString["lang"].IsEmpty())
    {
        Culture = UICulture = Request.QueryString["lang"];
    }
    else
    {
        Culture = UICulture = ViewBag.Localize ?? "en";
    }


}
@section Scripts {
    <script>
        $('#loadingAnimation').css('visibility', 'hidden');
    function ShowProgress() {
        setTimeout(function () {
            $('#loadingAnimation').css('visibility', 'visible');
        }, 200);
    }
    $('form').live("submit", function () {
        ShowProgress();
    });
    </script>
}
<div class="col-sm-3"></div>
<div class="col-sm-6" id="MessageView">
    <div class="preloader" id="loadingAnimation"  style="visibility:hidden">
        <div class="sk-cube-grid preloader-center center-block">
            <div class="sk-cube sk-cube1"></div>
            <div class="sk-cube sk-cube2"></div>
            <div class="sk-cube sk-cube3"></div>
            <div class="sk-cube sk-cube4"></div>
            <div class="sk-cube sk-cube5"></div>
            <div class="sk-cube sk-cube6"></div>
            <div class="sk-cube sk-cube7"></div>
            <div class="sk-cube sk-cube8"></div>
            <div class="sk-cube sk-cube9"></div>
        </div>
    </div>
    <button type="button" class="closebtn pull-right" onclick="location.href='/Home/Welcome'"
            style="font-size:50px;background-color:transparent;border:2px;width:70px; height:70px;margin-right:2%;margin-top:-1%">
        ×
    </button>
    <div class="row center-block" style="margin-top:10%;">
        <div class="col-sm-12">
            <div class="row text-center">
                <img src="~/Resources/sad.png" style="max-width: 800px; max-height: 600px" />
            </div>
            <div class="row">
                <div class="col-md-12">
                    <div class="row">
                        <div class="text-md-center">
                            <h2 class="text-center">@Resources.Resource.SORRY</h2>
                        </div>
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="col-sm-2"></div>
                <div class="col-md-8">
                    <div class="row">
                        <div class="text-md-center">
                            <p class="text-center">
                                @Resources.Resource.NOT_FOUND
                            </p>
                        </div>
                    </div>
                    <hr />
                    <div class="row">
                        <div class="text-md-center">
                            <p class="text-center">
                                <a href="@Url.Action("Welcome", "Home")" style="font-size:14px; text-decoration: none"><b>@Resources.Resource.TO_MAIN_PAGE</b></a>
                            </p>
                        </div>
                    </div>
                </div>
                <div class="col-sm-2"></div>
            </div>
        </div>
    </div>
</div>
<div class="col-sm-3"></div>

ScreenTaker/Views/Home/PartialImagesAccess.cshtml
@{
        if (!Request.QueryString["lang"].IsEmpty())
        {
            Culture = UICulture = Request.QueryString["lang"];
        }
        else
        {
            Culture = UICulture = ViewBag.Localize ?? "en";
        }
    
}
<div class="modal-header">
    <button type="button" class="close btn-not-rounded" data-dismiss="modal" aria-label="Close">
        <span aria-hidden="true">&times;</span>
    </button>
    <h4 class="modal-title" id="gridSystemModalLabel">@Resources.Resource.MANAGE_ACCESS</h4>
</div>
<div class="modal-body">
    <div class="row">
        <div class="col-sm-12">
            <input type="text" id="sharedLink1" style="height: 30px;" 
                   onclick="document.getElementById('sharedLink1').select();"
                   class="form-control" value="@ViewBag.ImageSharedLink" readonly>
        </div>
    </div>
    <div class="row">
        <div class="col-sm-6">
            <div class="row" style="margin-bottom:10px;">
                <div class="col-sm-12">
                    <h5 style="vertical-align:middle;margin:0;margin-top:5px;">@Resources.Resource.PEOPLE</h5>
                </div>
            </div>
            <div class="row">
                <div class="col-sm-12">
                    <div class="list-group" style="height:auto;height:150px;overflow:auto;border:solid #E0E0E0 1px;">
                        @if (ViewBag.AllowedUsers != null)
                        {
                            for (int i = 0; i < ViewBag.AllowedUsers.Count; i++)
                            {
                                string classes = "list-group-item";
                                if (ViewBag.AreUserRightsInherited[i])
                                {
                                    classes += " disabled-list-group-item";
                                }
                                <div class="@classes">                                                                                                        
                                    <div  class="media-left" style="vertical-align: middle;" >                                        
                                    @if (ViewBag.AreUserRightsInherited[i])
                                    {
                                            <button disabled type="button" class="btn badge right" aria-label="Left Align">
                                                <span class="glyphicon glyphicon-remove glyphicon-th-large" aria-hidden="true"></span>
                                            </button>
                                    }
                                    else
                                    {
                                            <button type="button" class="btn badge right" aria-label="Left Align" 
                                                onclick="$('#loadingAnimation').css('visibility', 'visible');$.ajax({
                                                url: 'ImageAccessRemoveUser',
                                                data: {
                                                    email: '@ViewBag.AllowedUsers[i]',
                                                    imageId: document.getElementById('Idhidden').value,
                                                },
                                                success: function (data) {
                                                    $('#ImagesAccessDynamic').html(data);
                                                 if(document.getElementById('MessageContentFromPartial').value!='')
                                                        {
                                                            $('#Message').modal('show');
                                                            document.getElementById('MessageContent').innerHTML=document.getElementById('MessageContentFromPartial').value;
                                                            document.getElementById('MessageTitle').innerHTML='@Resources.Resource.ERR_TITLE';
                                                        }
                                                }
                                            });">
                                            <span class="glyphicon glyphicon-remove glyphicon-th-large" aria-hidden="true"></span>
                                        </button>
                                    }
                                    </div>
                                    <div class="media-body" style="vertical-align: middle">
                                        <h5 class="media-heading">@ViewBag.AllowedUsers[i]</h5>
                                    </div> 
                                </div>
                            }
                        }                                            
                    </div>
                </div>
            </div>
            <div class="row" style="margin-bottom:10px;">
                <div class="col-sm-12">
                    <div class="input-group">
                        <input type="email" id="userMail" class="form-control" placeholder="@Resources.Resource.EMAIL" aria-describedby="sizing-addon2" data-autocomplete-source="@Url.Action("AutocompleteSearchEmails", "Edit")"
                        onkeyup="CheckEmail(this)" onblur="CheckEmail(this)" onfocus="CheckEmail(this)" onchange="CheckEmail(this)" onmouseover="CheckEmail(this)">
                        <span class="input-group-addon btn btn-default" aria-label="Left Align" id="sizing-addon2" onmouseover="CheckEmail($('#userMail'))"
                              onclick="$('#loadingAnimation').css('visibility', 'visible');
                              $.ajax({
                            url: 'ImageAccessAddUser',
                            data: {
                                email: document.getElementById('userMail').value,
                                imageId: document.getElementById('Idhidden').value,        
                            },
                            success: function (data) {
                                $('#ImagesAccessDynamic').html(data);
                                if (document.getElementById('MessageContentFromPartial').value != '') {
                                    $('#Message').modal('show');
                                    document.getElementById('MessageContent').innerHTML = document.getElementById('MessageContentFromPartial').value;
                                    document.getElementById('MessageTitle').innerHTML = 'Error';
                                }
                            }
                        });">+</span>       
                    </div>
                </div>
            </div>
        </div>
        <div class="col-sm-6">
            <div class="row" style="margin-bottom:10px;">
                <div class="col-sm-12">
                    <h5 style="vertical-align:middle;margin:0;margin-top:5px;">@Resources.Resource.GROUPS</h5>
                </div>
            </div>
            <div class="row">
                <div class="col-sm-12">
                    <div class="list-group" style="height:auto;height:205px;overflow:auto;border:solid #E0E0E0 1px;">
                        @if (ViewBag.AllGroups != null)
                        {
                            for (int i = 0; i < ViewBag.AllGroups.Count; i++)
                            {
                                string classes = "";
                                if (ViewBag.AreGroupRightsInherited[i])
                                {
                                    classes = "disabled-list-group-item";
                                }
                                <div class="list-group-item @classes">
                                    <div class="material-switch media-left" style="vertical-align: middle">
                                        @if (ViewBag.GroupsAccess[i] || ViewBag.AreGroupRightsInherited[i])
                                        {
                                            if (!ViewBag.AreGroupRightsInherited[i])
                                            {
                                                <input id="foldersAccessSwitch @i" type="checkbox" checked />
                                            }
                                            else
                                            {
                                                <input id="foldersAccessSwitch @i" type="checkbox" checked disabled/>
                                            }
                                        }
                                        else
                                        {
                                            <input id="foldersAccessSwitch @i" type="checkbox" />
                                        }
                                        @if (!ViewBag.AreGroupRightsInherited[i]){
                                        <label for="foldersAccessSwitch @i" class="label-info" 
                                        onclick="$('#loadingAnimation').css('visibility', 'visible');$.ajax({
                                        url: 'ImageAccessSwitchGroupsAccess',
                                        data: {
                                            groupId: @ViewBag.GroupsIDs[i],
                                            imageId: document.getElementById('Idhidden').value,
                                        },
                                        success: function (data) {
                                            $('#ImagesAccessDynamic').html(data);
                                            if(document.getElementById('MessageContentFromPartial').value!='')
                                            {
                                                $('#Message').modal('show');
                                                document.getElementById('MessageContent').innerHTML=document.getElementById('MessageContentFromPartial').value;
                                                document.getElementById('MessageTitle').innerHTML='Error';
                                            }
                                        }
                                        });" />
                                        }
                                        else{
                                        <label for="foldersAccessSwitch @i" class="label-info" onclick=""/>
                                        }
                                    </div>
                                    <div class="media-body" style="vertical-align: middle">
                                        <h5 class="media-heading">@ViewBag.AllGroups[i]</h5>
                                    </div>
                                </div>
                            }
                        }
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
@if (ViewBag.MessageContent != null)
{
    <input type="hidden" id="MessageContentFromPartial" value="@ViewBag.MessageContent" />
}
else
{
    <input type="hidden" id="MessageContentFromPartial" value="" />
}

<script src="~/Scripts/Site.js"></script>

ScreenTaker/Views/Home/PartialSingleImageMoveCreateFolder.cshtml
@{ 
    if (!Request.QueryString["lang"].IsEmpty())
    {
        Culture = UICulture = Request.QueryString["lang"];
    }
    else
    {
        Culture = UICulture = ViewBag.Localize ?? "en";
    }
}
@if (ViewBag.UserFolders != null && ViewBag.UserFolders.Count > 0)
{
    for (int i = 0; i < ViewBag.UserFolders.Count; i++)
    {
        string folderTitle = ViewBag.UserFolders[i].Name;
        <div class="list-group-item" title="@folderTitle">
            <div class="media-body" style="vertical-align:middle">
                <h5 class="media-heading text-overflowed text-overflowed_300">@folderTitle</h5>
            </div>
            <div class="media-right" style="vertical-align:middle;">
                <button type="button" class="btn right btn-primary btn-not-rounded" aria-label="Left Align" onclick="location.href='@Url.Action("MoveItMoveIt","Home",new {folderId=ViewBag.UserFolders[i].Id, imageSharedCode=ViewBag.Image.SharedCode})'">
                   @Resources.Resource.MOVE_HERE
                </button>
            </div>
        </div>
    }
}